graph TD
src --> shared
src --> user
src --> order
src --> auth

    shared --> domain
    shared --> infrastructure
    shared --> application

    user --> domain
    user --> infrastructure
    user --> application

    order --> domain
    order --> infrastructure
    order --> application

    domain --> model
    domain --> repository
    domain --> service

    infrastructure --> api
    infrastructure --> persistence

    application --> dto
    application --> commands
    application --> queries
